name: e2e-test

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions: {}

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      # Replace @main with the commit hash of the latest commit on the pull request branch
      - uses: nilsreichardt/verify-safe-to-test-label@main