name: e2e-test

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      # Use the action from the PR branch (current checkout). Used to check that
      # the action starts correctly (e.g. no dependencies issues, etc.).
      - uses: ./