name: e2e

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]


permissions: {}

jobs:
  start-action:
    permissions:
      contents: read # Recommended for actions/checkout action, see https://github.com/actions/checkout?tab=readme-ov-file#recommended-permissions
      pull-requests: write # Required for verify-safe-to-test-label action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      # Use the action from the PR branch (current checkout). Used to check that
      # the action starts correctly (e.g. no dependencies issues, etc.).
      - uses: ./

  test:
    needs: start-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - run: npm ci
      - run: npm run test:e2e
